---
- name: Hidden tomcat version number
  block:
    - name: Uncompass the catalina Java ARchive
      unarchive:
        src: '{{ tomcat_path }}/tomcat/lib/catalina.jar'
        dest: '{{ tomcat_path }}/tomcat/lib'
        remote_src: yes
    - name: Erase tomcat version
      lineinfile:
        state: present
        dest: '{{ tomcat_path }}/tomcat/lib/org/apache/catalina/util/ServerInfo.properties'
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      loop:
        - { regexp: '^server.info',   line: 'server.info=' }
        - { regexp: '^server.number', line: 'server.number=' }
        - { regexp: '^server.built',  line: 'server.built=' }
    - name: Compass the catalina Java ARchive 
      shell: 'cd {{ tomcat_path }}/tomcat/lib && jar cf catalina.jar META-INF/ org/'
    - name: Cleanup the uncompass file
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - '{{ tomcat_path }}/tomcat/lib/org'
        - '{{ tomcat_path }}/tomcat/lib/META-INF'

- name: Restrict access to tomcat directory
  file:
    path: '{{ item }}'
    owner: '{{ tomcat_arg.user }}'
    group: '{{ tomcat_arg.user }}'
    mode: 'o-rwx'
  loop: '{{ restrict_path }}'
